#!/usr/bin/env python3
"""Generate repository-local Codex pointers from a single route registry."""
import argparse
import json
import os
from pathlib import Path
import re
import tempfile

ROOT = Path(__file__).resolve().parents[2]


def safe_path(root, relative):
    rel = Path(relative)
    if rel.is_absolute() or '..' in rel.parts or not rel.parts:
        raise ValueError('path must stay inside repository: ' + str(relative))
    root = root.resolve()
    for part in [rel, *rel.parents]:
        path = root / part
        if path.is_symlink():
            raise ValueError('symlinked path: ' + str(part))
        if part != rel and path.exists() and not path.is_dir():
            raise ValueError('ancestor is not a directory: ' + str(part))
    return root / rel


def load_routes(root=ROOT):
    doc = json.loads(safe_path(root, '_system/scripts/wrapper-contract.json').read_text())
    if doc.get('version') != 1 or not isinstance(doc.get('commands'), dict):
        raise ValueError('invalid wrapper contract')
    for name, route in doc['commands'].items():
        if not re.fullmatch(r'[a-z][a-z0-9]*(?:-[a-z0-9]+)*', name):
            raise ValueError('invalid command name')
        if set(route) != {'description', 'workflow', 'required', 'optional', 'effects'}:
            raise ValueError('invalid route fields: ' + name)
        if not isinstance(route['description'], str) or not route['description'].strip():
            raise ValueError('missing description')
        if route['workflow'] != f'workflows/{name}/CONTEXT.md':
            raise ValueError('unexpected workflow contract path')
        if not safe_path(root, route['workflow']).is_file():
            raise ValueError('missing workflow contract: ' + name)
        for field in ('required', 'optional', 'effects'):
            if not isinstance(route[field], list) or any(not isinstance(x, str) for x in route[field]):
                raise ValueError('invalid capabilities: ' + name)
    return doc['commands']


def expected(root=ROOT):
    files = {}
    routes = load_routes(root)
    for name, row in routes.items():
        files[Path(f'.agents/skills/{name}/SKILL.md')] = (
            f'---\nname: {name}\ndescription: {json.dumps(row["description"])}\n---\n\n'
            'Read [AGENTS.md](../../../AGENTS.md), then '
            f'[the workflow contract](../../../{row["workflow"]}).\n'
            'Follow its declared dependencies and approval rules. Resolve repository paths\n'
            'from the root containing AGENTS.md. If a dependency is missing, stop that step\n'
            'and report it. This pointer grants no approval.\n'
        )
    lines = [
        '<!-- Generated by _system/scripts/wrappers.py. Edit the route registry. -->',
        '# Choose a sales workflow', '',
        'Start with one folder contract. Its Inputs table names the sections to load',
        'for each branch. Follow its Process, applicable Checkpoints, Audit and Outputs.', '',
        '| Workflow | Folder contract | Purpose |', '|---|---|---|',
    ]
    for name, row in routes.items():
        purpose = row['description'].split('. Use ', 1)[0].rstrip('.')
        lines.append(f'| `{name}` | [{row["workflow"]}]({row["workflow"]}) | {purpose} |')
    lines += ['', 'For first use or upgrades, follow [setup](setup/CONTEXT.md).',
              'Shared policy and evidence rules live in [_shared](_shared/CONTEXT.md).',
              'Maintenance tools and tests live in [_system](_system/CONTEXT.md).', '']
    files[Path('CONTEXT.md')] = '\n'.join(lines)
    return files


def render(root=ROOT, check=False):
    files = expected(root)
    safe_path(root, '.agents/skills')
    actual = {p.relative_to(root) for p in (root / '.agents/skills').glob('*/SKILL.md')}
    errors = ['unexpected pointer: ' + str(p) for p in sorted(actual - files.keys())]
    for rel in files:
        path = safe_path(root, rel)
        if path.exists() and not path.is_file():
            errors.append('pointer is not a file: ' + str(rel))
    if errors:
        return errors
    for rel, body in files.items():
        dest = root / rel
        if check:
            if not dest.exists() or dest.read_text() != body:
                errors.append('pointer drift: ' + str(rel))
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(mode='w', dir=dest.parent, delete=False) as stream:
                stream.write(body)
                tmp = Path(stream.name)
            tmp.chmod(0o644)
            os.replace(tmp, dest)
    return errors


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        errors = render(check=args.check)
    except (ValueError, OSError, TypeError) as exc:
        errors = [str(exc)]
    print('\n'.join(errors) if errors else 'Seven Codex workflow pointers and the root map match their routes.')
    raise SystemExit(bool(errors))
